### ISSUE TITLE
ERROR: GeMoMa died with error running GAF

### ISSUE THREAD

**Issue by JonEilers** [molevol-ub/bitacora#2]
Hi, Bitacora returns this error and I am not sure what to do with it. 

```bash
----------------- Starting mdYUCCA Genomic Gene Identification and Annotation
Doing mdYUCCA tblastn
Parsing mdYUCCA tblastn
Using GeMoMa to predict novel genes
ERROR in /Users/jeilers/Desktop/pyrus_research/bitacora/Scripts/runanalysis_2ndround_genomic_nogff_gemoma: GeMoMa died with error runnning GAF
BITACORA died with error
```

below is the rest of the command line output
```bash
#######################  Running BITACORA Genome mode  #######################
BITACORA genome-mode version 1.3
Wed Oct 28 17:55:55 PDT 2020

----------------- Checking input data and prerequisites
Genome fasta parsed correctly
HMMER installed correctly
BLAST installed correctly
GeMoMa-1.7.1 is installed correctly
Query directory files found and named correctly in /Users/jeilers/Desktop/pyrus_research/bitacora/files_used_bitacora_YUCCA
Found 1 query databases to search: mdYUCCA 
Everything looks fine
----------------- DONE

Indexing and translating genome file /Users/jeilers/Desktop/pyrus_research/pyrus_genome/PyrusCommunis_BartlettDHv2.0.fa
Translating genome... It may take a while
Translation completed for /Users/jeilers/Desktop/pyrus_research/pyrus_genome/PyrusCommunis_BartlettDHv2.0.fa


Building a new DB, current time: 10/28/2020 18:00:20
New DB name:   /Users/jeilers/Desktop/pyrus_research/pyrus_genome/PyrusCommunis_BartlettDHv2.0.fa
New DB title:  /Users/jeilers/Desktop/pyrus_research/pyrus_genome/PyrusCommunis_BartlettDHv2.0.fa
Sequence type: Nucleotide
Keep MBits: T
Maximum file size: 1000000000B
Adding sequences from FASTA; added 494 sequences in 3.46643 seconds.
```

**Comment by Vizueta** [comment]
Hi Jon,

Sorry to hear that you are getting an error running BITACORA. There should be a file inside the generated output folder (mdYUCAA in your case) named gemoma.err which will detail why the GAF module of GeMoMa failed. Could you please post this file, and, if possible, upload the whole output folder to investigate this error?

Best,
Joel

**Comment by Vizueta** [comment]
Hello Jon,

Ok, the error that you are obtaining when running the "GeMoMa GAF" step is caused because of the java environment used which seems not to be compatible with GeMoMa software. I tried running it both in Mac and Linux and it worked fine using java "1.8.0_271". 
I suggest you install JAVA SE 8 from here: https://www.oracle.com/java/technologies/javase-downloads.html. If you have multiple versions of java you can just switch to the mentioned version. 

I attach here the output with the generated annotation in that step: [filtered_predictions.gff.txt](https://github.com/molevol-ub/bitacora/files/5471156/filtered_predictions.gff.txt)
Please let me know if are able to run BITACORA or need any additional help :)

Best,
Joel

**Comment by JonEilers** [comment]
Thanks! I have java version 15 installed on my macbook. I installed Java 8 into my bitacora conda environment using this [conda package](https://anaconda.org/cyclus/java-jdk) and it appears to have worked.
